---
- name: Pull docker image of app
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull app devops image
      docker_image:
        name: khushalabrol2000/scientific_calculator
        source: pull
