---
- name: Pull docker image of Scientific Calculator
  hosts: all
  tasks:
    - name: Stop Docker container
      docker_container: 
        name: calc
        state: stopped

    - name: Remove Docker container
      docker_container: 
        name: calc
        state: absent 
        
    - name: Remove Docker image
      docker_image:
        state: absent
        name: khushalabrol2000/scientific_calculator
        tag: latest 
        
    - name: Pull devops image
      docker_image:
        name: khushalabrol2000/scientific_calculator
        source: pull

    - name: deploy calc docker container
      docker_container:
        image: khushalabrol2000/scientific_calculator:latest
        name: calc
        state: started
        auto_remove: true
        ports:
          - "3221:80"
... 
